name = "Adrenaline"
author = "SkywardMC"
version = "1.23.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "826d70933c0a64e2a498cdb3320f48ae1b999323ddce285f8404915000bf7b6e"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
