name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f45509689f20811cb1350f0984d2eab69cf2d281314f117d34e009a148821249"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
