name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79a70d1b35f7d8f66040bab72ae527ab73d14a122c2c6356a492fe8300147fa7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
