name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "def59c7c26664daf43df68bfda09e95e5fc3582e2af7ef192f8ec66f6aebbe10"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
