name = "Adrenaline"
author = "SkywardMC"
version = "1.26.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66304d05a980eaa00051b71f15e35c9b735a4546906f654dc16bb3798c6c1858"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
