name = "Adrenaline"
author = "SkywardMC"
version = "1.27.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7041c48391f2ba3205e564d006bd8571d31e293897392fb7d64517f6aafd4ac6"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
