name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a1efd25ff23c6ff07c84fbe728b04a2ffa49f3690138acad737e8beaf00fbd7"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
