name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33baec15a7c771c8f1fc656ba55c82e0f6cd955709a185636b94063aba6fdc16"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
