name = "Adrenaline"
author = "SkywardMC"
version = "1.23.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab47abb38af36490aae8f2dde5c5c994a0f34a42c32af25e46131db6622caa89"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
