name = "Adrenaline"
author = "SkywardMC"
version = "1.28.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74f0bb6e7e60cf5f87bad22c7239f7178aafc1d960b7cad6b2e59c3fbbad8376"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
