name = "Adrenaline"
author = "SkywardMC"
version = "1.28.0+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e25db3eb806286cb34b39a7f01e20aa285a8932e5217f65fa096b69db161868"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
