name = "Adrenaline"
author = "SkywardMC"
version = "1.30.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8af561b0030dcfa4ce8241a450a4712dabd41c8686a0e3017a15bb12f2c8f27d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
