name = "Adrenaline"
author = "SkywardMC"
version = "1.29.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e41bb5bd912fb621d1200e4a66fd77200842b11742c6c5c3bc47d2da68486fe0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
