name = "Adrenaline"
author = "SkywardMC"
version = "1.29.1+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43c1f0bf44a20c44289dfd4c133719ef3e7f050fee9408f309149b29f82cbb8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
