name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "688620339b4c3aa2a321695a0b6b2569f41f234a91503a1c1834eaaa9c48180a"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
