name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "541f38af8c1de0acdc5ebbc853432ae66059e4ed786e076f1e7140aaff1ef909"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
