name = "Adrenaline"
author = "SkywardMC"
version = "1.23.1+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcbb944d60b00623f4f65faabb0d8752dc5f7ce358bf5e4d96e65801db1d38ab"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
