name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5ad405213755abc5b30360abe39bb52cf937991e80497287bf015c605ffbc8f"

[versions]
fabric = "0.16.7"
minecraft = "1.20.4"
