name = "Adrenaline"
author = "SkywardMC"
version = "1.24.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98b9997058c243d864706f1573e3e0538c25ae0f73adcae50c748ebf27e6677a"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
