name = "Adrenaline"
author = "SkywardMC"
version = "1.23.1+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c915310baeda89d7a087e382dbd8298e34833d78373885a462fd8472d1595a6"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
