name = "Adrenaline"
author = "SkywardMC"
version = "1.31.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3304ef12014cc7f37c528bdd279b41b50b88258c02d4d20129e9078a08807dd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
