name = "Adrenaline"
author = "SkywardMC"
version = "1.26.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e2f22b633a2beb31c41b564cdeeb0821a1f943b17a4bdc4de6029735cd85338"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
