name = "Adrenaline"
author = "SkywardMC"
version = "1.28.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b43b7f68a11d5004895999e0fa56fea6279a150a387197432b34b5eaa82248f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
