name = "Adrenaline"
author = "SkywardMC"
version = "1.29.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4673df4427b5a5d868b57c5b1d28250e3b24ed8c6c19d448d79a18d2e04ad98"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
