name = "DMC+"
author = "Alas"
version = "1.4.0a+DMC"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b914dbbfefc8820473692ab1a13d6962f807c924952a7d3775c9c2e21e443f0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
