name = "EMC+"
author = "Alas"
version = "1.4.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae40e0ce0f0874f34b813d5ffce1c4f80f908abdbe048ac492b2b1da7a0de8ef"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
