name = "Adrenaline"
author = "SkywardMC"
version = "1.26.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c03c26266412deb92811c6c6d162a5549ac230c37d2d29dc3beb5b50a84d1996"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
