name = "Adrenaline"
author = "SkywardMC"
version = "1.27.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78479ed445e08af4621d9c60c4e010cb2bcbf37090bc7390f03f2e2bfbea0605"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
