name = "Adrenaline"
author = "SkywardMC"
version = "1.29.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c734afb5c091a892c310db63610617dcc3369d6950c59324d26221cdadc6e468"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
