name = "Adrenaline"
author = "SkywardMC"
version = "1.28.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c48bcd12ad34a92f0dfb1774691a03a538735bff17b8562deb6a0155c90e746"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
