name = "Adrenaline"
author = "SkywardMC"
version = "1.30.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffddd5867d6120c3047d386c54ad011f9148ef1590d0dc31e39853c0754029d0"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
