name = "Adrenaline"
author = "SkywardMC"
version = "1.23.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73f6109a36c5bdec3d9997e7a222785a12d79a40b8a29f20df3a39d3baa52699"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
