name = "Adrenaline"
author = "SkywardMC"
version = "1.27.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9ebe454a9da7b0255e2aeee27053388a5886d088acf013ac7d6515eeb5ae721"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
