name = "Adrenaline"
author = "SkywardMC"
version = "1.31.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d5b010ad8b35e0f0aba82dba8da419ae45bd50f5a2d18f3b509bb06f2b7b329"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
