name = "Adrenaline"
author = "SkywardMC"
version = "1.27.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef8764e819d77e320a9b4d52dee8c29daf5b005bb172af5e54aca59967d3b0fe"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
